# Generated by Django 3.0.2 on 2020-01-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('cve_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CVE Id')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Published Date')),
                ('last_modified_date', models.DateField(blank=True, null=True, verbose_name='Last Modified Date')),
                ('affected_products', models.IntegerField(blank=True, null=True, verbose_name='Number of Affected Products')),
                ('cvss_v2_base_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='CVSS V2 Base Score')),
                ('cvss_v2_severity', models.CharField(blank=True, max_length=20, null=True, verbose_name='CVSS V2 Severity')),
                ('cvss_v2_vector_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='CVSS V2 Vector String')),
                ('cvss_v3_base_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='CVSS V3 Base Score')),
                ('cvss_v3_severity', models.CharField(blank=True, max_length=20, null=True, verbose_name='CVSS V3 Severity')),
                ('cvss_v3_vector_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='CVSS V3 Vector String')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('source', models.CharField(max_length=20, verbose_name='Ref Source')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
                ('cve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CVE')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vulnerable', models.BooleanField()),
                ('uri', models.CharField(max_length=500, verbose_name='cpe23Uri')),
                ('cve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CVE')),
            ],
        ),
    ]
